(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const STATIONS=[['propaganda','Propaganda Radio'],['lizzy','Lizzy Radio'],['presidential','Presidential Radio']];
const MAX_UPLOAD=8*1024*1024,MAX_LIVE_MS=20*60*1000;
let snap=null,livePc=null,liveStream=null,liveMicStream=null,liveAudioCtx=null,liveRecorder=null,liveChunks=[],liveSession='',livePoll=null,liveTimer=null,liveStarted=0,liveStation='propaganda',liveEffect='fm';
async function api(a,b={}){if(!window.MikaelHQApi)throw Error('HQ API not ready');return MikaelHQApi(a,b)}
function workerUrl(){let w=String(localStorage.getItem('mickyhq_test_worker_url_v1')||'').trim();if(w&&!w.endsWith('/'))w+='/';return w}
function audioSrc(x){if(!x)return'';if(x.audioKey)return workerUrl()+'?radioAudio='+encodeURIComponent(x.audioKey);return x.url||x.audioUrl||''}
function stationName(id){return STATIONS.find(x=>x[0]===id)?.[1]||id}
function val(id){return $(id)?.value?.trim()||''}
function checkedStations(prefix){return STATIONS.filter(([id])=>$(prefix+id)?.checked).map(([id])=>id)}
function fileToDataUrl(file){return new Promise((res,rej)=>{if(!file)return res('');if(file.size>MAX_UPLOAD)return rej(Error('Keep HQ audio uploads under 8 MB. Larger songs should be bundled into TESTR.'));const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=()=>rej(Error('Could not read that audio file.'));r.readAsDataURL(file)})}
function waitIce(pc,ms=6500){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{const done=()=>{pc.removeEventListener('icegatheringstatechange',on);clearTimeout(t);resolve()};const on=()=>pc.iceGatheringState==='complete'&&done();pc.addEventListener('icegatheringstatechange',on);const t=setTimeout(done,ms)})}
function blobToDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=()=>rej(Error('Could not archive the live recording.'));r.readAsDataURL(blob)})}
function mediaRows(items,kind){if(!items?.length)return '<div class="radioRow">Nothing here yet.</div>';return items.map(x=>{const bundled=kind==='track'&&x.builtIn&&String(x.url||'').startsWith('radio-audio/'),src=bundled?'':audioSrc(x),built=x.builtIn?' <span class="radioSeed">BUILT-IN</span>':'',playable=bundled||!!src;return `<div class="radioRow radioMediaRow" data-media-row="${esc(kind)}:${esc(x.id)}"><div><b>${esc(x.title||'Untitled')}</b>${built}<small>${kind==='track'?esc(x.artist||''):kind==='ad'?esc(x.text||''):esc((x.kind||'')+' · '+stationName(x.station||''))}</small></div><div class="radioMediaActions">${playable?`<button class="primary small playNowBtn" data-play-media="${esc(kind)}:${esc(x.id)}">▶ PLAY NOW ON AIR</button>`:''}${bundled?`<span class="radioBundled">✓ Bundled directly in TESTR</span>`:src?`<audio controls preload="none" src="${esc(src)}"></audio>`:`<span class="radioNeeds">Needs audio</span><input type="file" accept="audio/*" data-attach-file="${esc(kind)}:${esc(x.id)}"><input placeholder="or audio URL" data-attach-url="${esc(kind)}:${esc(x.id)}"><button class="primary small" data-attach="${esc(kind)}:${esc(x.id)}">Attach</button>`}${!x.builtIn?`<button class="danger small" data-delete-media="${esc(kind)}:${esc(x.id)}">Delete</button>`:''}</div></div>`}).join('')}
function archiveRows(){const xs=(snap?.archive||[]).slice().reverse();if(!xs.length)return '<div class="radioRow">No archived broadcasts yet.</div>';return xs.slice(0,30).map(x=>{const src=audioSrc(x);return `<div class="radioRow"><b>${x.type==='live'?'🔴 LIVE ARCHIVE · ':''}${esc(x.title||'Broadcast')}</b><small>${esc(stationName(x.station))} · ${x.createdAt?new Date(x.createdAt).toLocaleString():''}</small>${x.effect?`<small>Voice effect: ${esc(effectName(x.effect))}</small>`:''}${x.text?`<div>${esc(x.text)}</div>`:''}${src?`<audio controls preload="none" src="${esc(src)}"></audio>`:''}<button class="danger small" data-archive-delete="${esc(x.id)}">Delete archive</button></div>`}).join('')}
async function load(){try{const d=await api('radio_hq_state');snap=d.state;render()}catch(e){if($('radioStatus'))$('radioStatus').textContent=e.message}}
function render(){if(!snap)return;$('radioStatus').textContent='🧪 TEST Worker synced · '+new Date().toLocaleTimeString();
 $('radioLiveStations').innerHTML=Object.entries(snap.stations||{}).map(([id,s])=>`<div class="radioRow"><span class="radioBadge">${esc(stationName(id))}</span><b>${esc(s.now?.title||'Idle')}</b><div>${esc(s.now?.subtitle||s.now?.text||'')}</div>${audioSrc(s.now)?`<audio controls preload="none" src="${esc(audioSrc(s.now))}"></audio>`:''}</div>`).join('');
 $('radioRequests').innerHTML=(snap.requests||[]).slice().reverse().map(r=>`<div class="radioRow"><b>${esc(r.kind==='song'?'Song request':'Request')}</b><div>${esc([r.song,r.artist].filter(Boolean).join(' — ')||r.note||'Voice request')}</div>${r.note?`<small>${esc(r.note)}</small>`:''}${r.audio?`<audio controls src="${esc(r.audio)}"></audio>`:''}</div>`).join('')||'<div class="radioRow">No requests yet.</div>';
 $('radioHijack').innerHTML=snap.hijack?.active?`<div class="radioRow"><b>🚨 Lizzy has seized Presidential Radio</b><p>${esc(snap.hijack.text||'Voice takeover')}</p>${snap.hijack.audio?`<audio controls src="${esc(snap.hijack.audio)}"></audio>`:''}<button class="danger" id="radioTakeBack">TAKE BACK CONTROL</button></div>`:'<div class="radioRow">No active hijack.</div>';
 if($('radioTakeBack'))$('radioTakeBack').onclick=async()=>{await api('radio_hq_takeback');load()};
 $('radioChallengeLive').innerHTML=snap.challenge?`<div class="radioRow"><b>${esc(snap.challenge.title)}</b><div>${esc(snap.challenge.instruction)}</div><strong>${Number(snap.challenge.prize||0)} MB</strong><br><small>${snap.challenge.completedAt?'✅ Auto-confirmed via #LizzyRadio':'Waiting for #LizzyRadio'}</small></div>`:'<div class="radioRow">No challenge live.</div>';
 $('radioTracks').innerHTML=mediaRows(snap.tracks||[],'track');$('radioAds').innerHTML=mediaRows(snap.ads||[],'ad');$('radioJingles').innerHTML=mediaRows(snap.jingles||[],'jingle');$('radioArchive').innerHTML=archiveRows();
 bindDynamic();populateNextPicker();renderLiveStatus();
}
function findMedia(kind,id){const xs=kind==='track'?snap?.tracks:kind==='ad'?snap?.ads:snap?.jingles;return (xs||[]).find(x=>String(x.id)===String(id))}
async function playMediaNow(kind,id,stationOverride=''){const item=findMedia(kind,id);if(!item)return alert('That radio item is no longer available.');let st=stationOverride||val('rpStation')||'propaganda';if(kind==='jingle'&&item.station)st=item.station;else if(Array.isArray(item.stations)&&item.stations.length&&!item.stations.includes(st))st=item.stations[0];try{await api('radio_hq_play_media',{kind,id,station:st});$('rpStation').value=st;$('radioManualStatus').textContent=`▶ Sent to ${stationName(st)}: ${item.title||'Radio audio'}`;await load()}catch(e){alert(e.message)}}
async function returnToShuffle(stationOverride=''){const st=stationOverride||val('rpStation')||'propaganda';try{await api('radio_hq_play_media',{kind:'shuffle',station:st});$('radioManualStatus').textContent=`🔀 ${stationName(st)} returned to automatic shuffle.`;await load()}catch(e){alert(e.message)}}
function populateNextPicker(){const sel=$('postLivePick');if(!sel||!snap)return;const rows=[];for(const [label,kind,xs] of [['Songs','track',snap.tracks||[]],['Jingles / Stings','jingle',snap.jingles||[]],['Fake Ads','ad',snap.ads||[]]]){const opts=xs.filter(x=>kind==='track'&&x.builtIn?true:!!audioSrc(x)).map(x=>`<option value="${esc(kind+':'+x.id)}">${esc(x.title||'Untitled')}</option>`).join('');if(opts)rows.push(`<optgroup label="${label}">${opts}</optgroup>`)}sel.innerHTML=rows.join('')||'<option value="">No playable radio audio yet</option>'}
function bindDynamic(){document.querySelectorAll('[data-attach]').forEach(b=>b.onclick=async()=>{const [kind,id]=b.dataset.attach.split(':');const file=document.querySelector(`[data-attach-file="${CSS.escape(kind+':'+id)}"]`)?.files?.[0],url=document.querySelector(`[data-attach-url="${CSS.escape(kind+':'+id)}"]`)?.value?.trim()||'';try{b.disabled=true;const audioData=await fileToDataUrl(file);await api('radio_hq_media_attach',{kind,id,url,audioData});await load()}catch(e){alert(e.message)}finally{b.disabled=false}});document.querySelectorAll('[data-play-media]').forEach(b=>b.onclick=()=>{const [kind,id]=b.dataset.playMedia.split(':');playMediaNow(kind,id)});document.querySelectorAll('[data-delete-media]').forEach(b=>b.onclick=async()=>{const [kind,id]=b.dataset.deleteMedia.split(':');if(!confirm('Delete this radio media item?'))return;try{await api('radio_hq_media_delete',{kind,id});load()}catch(e){alert(e.message)}});document.querySelectorAll('[data-archive-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this archived broadcast and its saved audio?'))return;try{await api('radio_hq_archive_delete',{id:b.dataset.archiveDelete});load()}catch(e){alert(e.message)}})}
function effectName(v){return({natural:'Natural Mic',fm:'FM Broadcast',warm:'Warm Studio',am:'AM / Vintage Radio',dispatch:'Emergency / Dispatch'})[v]||v||'FM Broadcast'}
function distortionCurve(amount=18){const n=44100,c=new Float32Array(n),deg=Math.PI/180;for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=(3+amount)*x*20*deg/(Math.PI+amount*Math.abs(x))}return c}
async function makeBroadcastStream(raw,preset){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return raw;liveAudioCtx=new AC();await liveAudioCtx.resume();const src=liveAudioCtx.createMediaStreamSource(raw),hp=liveAudioCtx.createBiquadFilter(),lp=liveAudioCtx.createBiquadFilter(),tone=liveAudioCtx.createBiquadFilter(),comp=liveAudioCtx.createDynamicsCompressor(),gain=liveAudioCtx.createGain(),dest=liveAudioCtx.createMediaStreamDestination();hp.type='highpass';lp.type='lowpass';tone.type='peaking';let useDist=false,dist=null;if(preset==='natural'){hp.frequency.value=60;lp.frequency.value=16000;tone.frequency.value=2200;tone.Q.value=.7;tone.gain.value=0;comp.threshold.value=-18;comp.ratio.value=2;gain.gain.value=1.0}else if(preset==='warm'){hp.frequency.value=70;lp.frequency.value=14000;tone.frequency.value=180;tone.Q.value=.7;tone.gain.value=3;comp.threshold.value=-25;comp.ratio.value=3.5;gain.gain.value=1.16}else if(preset==='am'){hp.frequency.value=260;lp.frequency.value=3600;tone.frequency.value=1500;tone.Q.value=.9;tone.gain.value=4;comp.threshold.value=-31;comp.ratio.value=7;gain.gain.value=.95;useDist=true}else if(preset==='dispatch'){hp.frequency.value=380;lp.frequency.value=3200;tone.frequency.value=1750;tone.Q.value=1.2;tone.gain.value=6;comp.threshold.value=-34;comp.ratio.value=9;gain.gain.value=.9;useDist=true}else{hp.frequency.value=90;lp.frequency.value=9500;tone.frequency.value=2300;tone.Q.value=.8;tone.gain.value=2.5;comp.threshold.value=-29;comp.ratio.value=5;gain.gain.value=1.22}comp.knee.value=18;comp.attack.value=.004;comp.release.value=.22;src.connect(hp);hp.connect(lp);lp.connect(tone);tone.connect(comp);if(useDist){dist=liveAudioCtx.createWaveShaper();dist.curve=distortionCurve(preset==='dispatch'?28:13);dist.oversample='2x';comp.connect(dist);dist.connect(gain)}else comp.connect(gain);gain.connect(dest);return dest.stream}
function renderLiveStatus(){const l=snap?.live,el=$('radioGoLiveStatus');if(!el)return;if(l?.active){const same=l.id===liveSession;el.innerHTML=`<b>🔴 ${esc(l.headline||'LIVE')}</b><br>${esc(stationName(l.station))}<br><small>${same?(livePc?.remoteDescription?'Listener connected / handshake complete':'Waiting for TESTR listener…'):'Live session active on the test network.'}</small>`}else el.textContent='Off air.'}
async function startLive(){if(liveStream)return alert('You are already live.');const station=val('rlStation'),headline=val('rlHeadline')||'Live from HQ',effect=val('rlEffect')||'fm';try{$('rlGo').disabled=true;$('rlEffect').disabled=true;$('radioGoLiveStatus').textContent='Opening microphone and broadcast processor…';liveMicStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false}});liveEffect=effect;liveStation=station;liveStream=await makeBroadcastStream(liveMicStream,effect);livePc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});liveStream.getTracks().forEach(t=>livePc.addTrack(t,liveStream));const offer=await livePc.createOffer({offerToReceiveAudio:false});await livePc.setLocalDescription(offer);await waitIce(livePc);liveSession='live_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);liveChunks=[];let opts={};if(MediaRecorder.isTypeSupported('audio/webm;codecs=opus'))opts={mimeType:'audio/webm;codecs=opus',audioBitsPerSecond:32000};else if(MediaRecorder.isTypeSupported('audio/webm'))opts={mimeType:'audio/webm',audioBitsPerSecond:32000};liveRecorder=new MediaRecorder(liveStream,opts);liveRecorder.ondataavailable=e=>{if(e.data?.size)liveChunks.push(e.data)};liveRecorder.start(1000);await api('radio_hq_live_start',{session:liveSession,station,headline,effect,offer:livePc.localDescription.sdp});liveStarted=Date.now();$('rlEnd').disabled=false;$('rlMute').disabled=false;$('radioGoLiveStatus').textContent=`🔴 LIVE · ${effectName(effect)} · waiting for TESTR listener…`;$('postLiveChooser').classList.remove('show');livePoll=setInterval(checkLiveAnswer,1800);liveTimer=setInterval(()=>{const secs=Math.floor((Date.now()-liveStarted)/1000),m=Math.floor(secs/60),ss=String(secs%60).padStart(2,'0');$('rlClock').textContent=`${m}:${ss}`;if(Date.now()-liveStarted>=MAX_LIVE_MS)endLive(true)},1000);await load()}catch(e){cleanupLive();alert('Could not go live: '+e.message)}finally{$('rlGo').disabled=!!liveStream}}
async function checkLiveAnswer(){if(!liveSession||!livePc||livePc.remoteDescription)return;try{const d=await api('radio_hq_state'),l=d.state?.live;if(l?.id===liveSession&&l.answer){await livePc.setRemoteDescription({type:'answer',sdp:l.answer});$('radioGoLiveStatus').textContent=`🔴 LIVE · ${effectName(liveEffect)} · TESTR listener connected ✓`}}catch(e){console.warn('live answer',e)}}
function toggleMute(){if(!liveStream)return;const t=liveStream.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;$('rlMute').textContent=t.enabled?'🔇 Mute Mic':'🎙 Unmute Mic'}
async function endLive(auto=false){if(!liveStream||!liveSession)return;const session=liveSession,endedStation=liveStation,effect=liveEffect;try{$('rlEnd').disabled=true;$('radioGoLiveStatus').textContent='Ending broadcast… saving the live recording first.';const rec=liveRecorder;const done=new Promise(resolve=>{if(!rec||rec.state==='inactive')return resolve();const t=setTimeout(resolve,2500);rec.addEventListener('stop',()=>{clearTimeout(t);resolve()},{once:true});try{rec.stop()}catch{resolve()}});await done;const blob=new Blob(liveChunks,{type:'audio/webm'});let audioData='';if(blob.size&&blob.size<=MAX_UPLOAD)audioData=await blobToDataUrl(blob);const result=await api('radio_hq_live_end',{session,audioData,effect});cleanupLive();await load();$('rpStation').value=endedStation;$('postLiveStation').value=endedStation;$('postLiveChooser').classList.add('show');$('radioGoLiveStatus').textContent=result.archiveWarning?`Broadcast ended. Archive metadata saved, but audio had a storage warning: ${result.archiveWarning}`:(auto?'Live ended automatically and was archived ✓':'Live ended and recording saved to archive ✓ · choose what plays next below.')}catch(e){try{await api('radio_hq_live_end',{session,audioData:'',effect})}catch{}cleanupLive();await load().catch(()=>{});$('radioGoLiveStatus').textContent='Live is off air, but the audio archive needs attention.';alert('The broadcast was ended, but saving its audio failed: '+e.message)}}
function cleanupLive(stopTracks=true){if(stopTracks)liveStream?.getTracks()?.forEach(t=>t.stop());liveMicStream?.getTracks()?.forEach(t=>t.stop());try{livePc?.close()}catch{}try{liveAudioCtx?.close()}catch{}clearInterval(livePoll);clearInterval(liveTimer);livePc=null;liveStream=null;liveMicStream=null;liveAudioCtx=null;liveRecorder=null;liveChunks=[];liveSession='';liveStarted=0;if($('rlGo'))$('rlGo').disabled=false;if($('rlEnd'))$('rlEnd').disabled=true;if($('rlMute')){$('rlMute').disabled=true;$('rlMute').textContent='🔇 Mute Mic'}if($('rlEffect'))$('rlEffect').disabled=false;if($('rlClock'))$('rlClock').textContent='0:00'}
function mount(){const nav=document.querySelector('nav');if(nav&&!nav.querySelector('[data-view="radio"]'))nav.insertAdjacentHTML('beforeend','<button data-view="radio">📻 Radio Control</button>');const main=document.querySelector('main');if(!main||$('radio'))return;main.insertAdjacentHTML('beforeend',`<section id="radio" class="view hidden"><div class="section-intro"><div><span class="pill">🧪 TEST RADIO NETWORK</span><h2>📻 LizzyOS Radio Control</h2><p>Test-only radio control. Bundled songs play from TESTR; uploaded ads, jingles and live archives stay on the TEST Worker.</p></div><div class="intro-actions"><button class="primary" id="radioRefresh">↻ Refresh</button></div></div><div id="radioStatus" class="meta"></div><div class="radioGrid">
<div class="radioCard liveCard"><h3>🔴 Go Live from HQ</h3><select id="rlStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><input id="rlHeadline" placeholder="Breaking-news headline / live show title"><label class="radioLabel">🎚 Live voice effect<select id="rlEffect"><option value="fm" selected>FM Broadcast — polished radio voice</option><option value="warm">Warm Studio — fuller presenter sound</option><option value="am">AM / Vintage Radio — narrow old-radio sound</option><option value="dispatch">Emergency / Dispatch — compressed communications</option><option value="natural">Natural Mic — light processing only</option></select></label><div class="liveControls"><button class="danger" id="rlGo">🎙 GO LIVE</button><button id="rlMute" disabled>🔇 Mute Mic</button><button id="rlEnd" disabled>⏹ Save & End</button><strong id="rlClock">0:00</strong></div><div id="radioGoLiveStatus" class="liveStatus">Off air.</div><div id="postLiveChooser" class="postLiveChooser"><b>✅ Broadcast saved. What should play next?</b><select id="postLiveStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><select id="postLivePick"></select><div class="postLiveActions"><button class="primary" id="postLivePlay">▶ Play Selected</button><button id="postLiveShuffle">🔀 Return to Shuffle</button></div></div><small>Your selected voice effect is applied before Lizzy hears you and before the live audio is archived. Test archive limit: 20 minutes / 8 MB.</small></div>
<div class="radioCard"><h3>🎛 On-Air Manual Control</h3><select id="rpStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><p>Use <b>PLAY NOW ON AIR</b> beside any saved song, jingle or advert below. When the selected item ends, the station automatically goes back to random rotation.</p><button id="rpShuffle">🔀 Return to Automatic Shuffle Now</button><div id="radioManualStatus" class="liveStatus manualStatus">Automatic shuffle is available whenever HQ is not choosing audio.</div></div>
<div class="radioCard"><h3>Broadcast Now</h3><select id="rbStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><input id="rbTitle" placeholder="Headline / show title"><textarea id="rbText" placeholder="Broadcast text"></textarea><input id="rbAudio" placeholder="Optional audio URL/path"><input id="rbFile" type="file" accept="audio/*"><button class="primary" id="rbSend">Send Broadcast</button></div>
<div class="radioCard"><h3>Schedule Programme</h3><select id="rsStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><input id="rsTime" type="time" step="60" value="08:00"><input id="rsTitle" placeholder="Show title"><textarea id="rsText" placeholder="Optional show description"></textarea><button class="primary" id="rsAdd">Add Schedule</button><small>Schedule uses 24-hour HH:MM time.</small></div>
<div class="radioCard"><h3>Lizzy Radio Challenge</h3><input id="rcTitle" placeholder="Challenge title"><textarea id="rcInstruction" placeholder="e.g. Send Mikael a cute message with #LizzyRadio"></textarea><input id="rcPrize" type="number" min="0" placeholder="Prize MB"><button class="primary" id="rcStart">Start Challenge</button><div id="radioChallengeLive"></div></div>
<div class="radioCard wide"><h3>🎵 Music Library</h3><div class="radioForm"><input id="rmTitle" placeholder="Song title"><input id="rmArtist" placeholder="Artist"><input id="rmUrl" placeholder="Audio URL/path"><input id="rmFile" type="file" accept="audio/*"><div class="radio3">${STATIONS.map(([id,n])=>`<label><input type="checkbox" id="rm_${id}" checked> ${n.replace(' Radio','')}</label>`).join('')}</div><button class="primary" id="rmAdd">Add Track</button></div><div id="radioTracks" class="radioRows scrollRows"></div></div>
<div class="radioCard wide"><h3>📢 Fake Ad Library</h3><div class="radioForm"><input id="raTitle" placeholder="Company / advert name"><textarea id="raText" placeholder="Advert slogan / script"></textarea><select id="raFrequency"><option value="rare">Rare</option><option value="normal" selected>Normal</option><option value="frequent">Frequent</option></select><input id="raUrl" placeholder="Audio URL/path"><input id="raFile" type="file" accept="audio/*"><div class="radio3">${STATIONS.map(([id,n])=>`<label><input type="checkbox" id="ra_${id}" checked> ${n.replace(' Radio','')}</label>`).join('')}</div><button class="primary" id="raAdd">Add Advertisement</button></div><div id="radioAds" class="radioRows scrollRows"></div></div>
<div class="radioCard wide"><h3>🔊 Jingle / Breaking Sting Library</h3><div class="radioForm"><input id="rjTitle" placeholder="Jingle name"><select id="rjStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><select id="rjKind"><option value="station">Station ID / opening</option><option value="show">Show transition</option><option value="breaking">Breaking-news sting</option></select><input id="rjUrl" placeholder="Audio URL/path"><input id="rjFile" type="file" accept="audio/*"><button class="primary" id="rjAdd">Add Jingle</button></div><div id="radioJingles" class="radioRows scrollRows"></div></div>
<div class="radioCard"><h3>Live Stations</h3><div id="radioLiveStations" class="radioRows"></div></div><div class="radioCard"><h3>Song / Voice Requests</h3><div id="radioRequests" class="radioRows"></div></div><div class="radioCard"><h3>Hijack Control</h3><div id="radioHijack"></div></div><div class="radioCard wide"><h3>🗃 Broadcast Archive</h3><div id="radioArchive" class="radioRows scrollRows"></div></div></div></section>`);
 nav?.querySelector('[data-view="radio"]')?.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));nav.querySelector('[data-view="radio"]').classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('radio').classList.remove('hidden');$('viewTitle').textContent='LizzyOS Radio Control';load()});
 $('radioRefresh').onclick=load;$('rlGo').onclick=startLive;$('rlMute').onclick=toggleMute;$('rlEnd').onclick=()=>endLive(false);$('rpShuffle').onclick=()=>returnToShuffle();$('postLiveShuffle').onclick=()=>returnToShuffle(val('postLiveStation'));$('postLivePlay').onclick=()=>{const v=val('postLivePick');if(!v)return alert('Choose a song, jingle or advert.');const i=v.indexOf(':');playMediaNow(v.slice(0,i),v.slice(i+1),val('postLiveStation'));};
 $('rbSend').onclick=async()=>{try{const audioData=await fileToDataUrl($('rbFile').files[0]);await api('radio_hq_broadcast',{station:val('rbStation'),title:val('rbTitle'),text:val('rbText'),audioUrl:val('rbAudio'),audioData});$('rbTitle').value='';$('rbText').value='';$('rbAudio').value='';$('rbFile').value='';load()}catch(e){alert(e.message)}};
 $('rsAdd').onclick=async()=>{try{await api('radio_hq_schedule',{station:val('rsStation'),time:val('rsTime'),title:val('rsTitle'),text:val('rsText')});load()}catch(e){alert(e.message)}};
 $('rcStart').onclick=async()=>{try{await api('radio_hq_challenge',{title:val('rcTitle'),instruction:val('rcInstruction'),prize:Number(val('rcPrize')||0)});load()}catch(e){alert(e.message)}};
 $('rmAdd').onclick=async()=>{try{const audioData=await fileToDataUrl($('rmFile').files[0]);await api('radio_hq_track',{title:val('rmTitle'),artist:val('rmArtist'),url:val('rmUrl'),audioData,stations:checkedStations('rm_')});$('rmFile').value='';load()}catch(e){alert(e.message)}};
 $('raAdd').onclick=async()=>{try{const audioData=await fileToDataUrl($('raFile').files[0]);await api('radio_hq_ad',{title:val('raTitle'),text:val('raText'),frequency:val('raFrequency'),url:val('raUrl'),audioData,stations:checkedStations('ra_')});$('raFile').value='';load()}catch(e){alert(e.message)}};
 $('rjAdd').onclick=async()=>{try{const audioData=await fileToDataUrl($('rjFile').files[0]);await api('radio_hq_jingle',{title:val('rjTitle'),station:val('rjStation'),kind:val('rjKind'),url:val('rjUrl'),audioData});$('rjFile').value='';load()}catch(e){alert(e.message)}};
}
window.addEventListener('beforeunload',()=>{liveStream?.getTracks()?.forEach(t=>t.stop());liveMicStream?.getTracks()?.forEach(t=>t.stop());try{liveAudioCtx?.close()}catch{}});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
