(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const STATIONS=[['propaganda','Propaganda Radio'],['lizzy','Lizzy Radio'],['presidential','Presidential Radio']];
const MAX_UPLOAD=8*1024*1024,MAX_LIVE_MS=20*60*1000;
let snap=null,livePc=null,liveStream=null,liveRecorder=null,liveChunks=[],liveSession='',livePoll=null,liveTimer=null,liveStarted=0;
async function api(a,b={}){if(!window.MikaelHQApi)throw Error('HQ API not ready');return MikaelHQApi(a,b)}
function workerUrl(){let w=String(localStorage.getItem('mickyhq_test_worker_url_v1')||'').trim();if(w&&!w.endsWith('/'))w+='/';return w}
function audioSrc(x){if(!x)return'';if(x.audioKey)return workerUrl()+'?radioAudio='+encodeURIComponent(x.audioKey);return x.url||x.audioUrl||''}
function stationName(id){return STATIONS.find(x=>x[0]===id)?.[1]||id}
function val(id){return $(id)?.value?.trim()||''}
function checkedStations(prefix){return STATIONS.filter(([id])=>$(prefix+id)?.checked).map(([id])=>id)}
function fileToDataUrl(file){return new Promise((res,rej)=>{if(!file)return res('');if(file.size>MAX_UPLOAD)return rej(Error('Keep HQ audio uploads under 8 MB. Larger songs should be bundled into TESTR.'));const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=()=>rej(Error('Could not read that audio file.'));r.readAsDataURL(file)})}
function waitIce(pc,ms=6500){if(pc.iceGatheringState==='complete')return Promise.resolve();return new Promise(resolve=>{const done=()=>{pc.removeEventListener('icegatheringstatechange',on);clearTimeout(t);resolve()};const on=()=>pc.iceGatheringState==='complete'&&done();pc.addEventListener('icegatheringstatechange',on);const t=setTimeout(done,ms)})}
function blobToDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result||''));r.onerror=()=>rej(Error('Could not archive the live recording.'));r.readAsDataURL(blob)})}
function mediaRows(items,kind){if(!items?.length)return '<div class="radioRow">Nothing here yet.</div>';return items.map(x=>{const bundled=kind==='track'&&x.builtIn&&String(x.url||'').startsWith('radio-audio/'),src=bundled?'':audioSrc(x),built=x.builtIn?' <span class="radioSeed">BUILT-IN</span>':'';return `<div class="radioRow radioMediaRow" data-media-row="${esc(kind)}:${esc(x.id)}"><div><b>${esc(x.title||'Untitled')}</b>${built}<small>${kind==='track'?esc(x.artist||''):kind==='ad'?esc(x.text||''):esc((x.kind||'')+' · '+stationName(x.station||''))}</small></div><div class="radioMediaActions">${bundled?`<span class="radioBundled">✓ Bundled directly in TESTR</span>`:src?`<audio controls preload="none" src="${esc(src)}"></audio>`:`<span class="radioNeeds">Needs audio</span><input type="file" accept="audio/*" data-attach-file="${esc(kind)}:${esc(x.id)}"><input placeholder="or audio URL" data-attach-url="${esc(kind)}:${esc(x.id)}"><button class="primary small" data-attach="${esc(kind)}:${esc(x.id)}">Attach</button>`}${!x.builtIn?`<button class="danger small" data-delete-media="${esc(kind)}:${esc(x.id)}">Delete</button>`:''}</div></div>`}).join('')}
function archiveRows(){const xs=(snap?.archive||[]).slice().reverse();if(!xs.length)return '<div class="radioRow">No archived broadcasts yet.</div>';return xs.slice(0,30).map(x=>{const src=audioSrc(x);return `<div class="radioRow"><b>${x.type==='live'?'🔴 LIVE ARCHIVE · ':''}${esc(x.title||'Broadcast')}</b><small>${esc(stationName(x.station))} · ${x.createdAt?new Date(x.createdAt).toLocaleString():''}</small>${x.text?`<div>${esc(x.text)}</div>`:''}${src?`<audio controls preload="none" src="${esc(src)}"></audio>`:''}<button class="danger small" data-archive-delete="${esc(x.id)}">Delete archive</button></div>`}).join('')}
async function load(){try{const d=await api('radio_hq_state');snap=d.state;render()}catch(e){if($('radioStatus'))$('radioStatus').textContent=e.message}}
function render(){if(!snap)return;$('radioStatus').textContent='🧪 TEST Worker synced · '+new Date().toLocaleTimeString();
 $('radioLiveStations').innerHTML=Object.entries(snap.stations||{}).map(([id,s])=>`<div class="radioRow"><span class="radioBadge">${esc(stationName(id))}</span><b>${esc(s.now?.title||'Idle')}</b><div>${esc(s.now?.subtitle||s.now?.text||'')}</div>${audioSrc(s.now)?`<audio controls preload="none" src="${esc(audioSrc(s.now))}"></audio>`:''}</div>`).join('');
 $('radioRequests').innerHTML=(snap.requests||[]).slice().reverse().map(r=>`<div class="radioRow"><b>${esc(r.kind==='song'?'Song request':'Request')}</b><div>${esc([r.song,r.artist].filter(Boolean).join(' — ')||r.note||'Voice request')}</div>${r.note?`<small>${esc(r.note)}</small>`:''}${r.audio?`<audio controls src="${esc(r.audio)}"></audio>`:''}</div>`).join('')||'<div class="radioRow">No requests yet.</div>';
 $('radioHijack').innerHTML=snap.hijack?.active?`<div class="radioRow"><b>🚨 Lizzy has seized Presidential Radio</b><p>${esc(snap.hijack.text||'Voice takeover')}</p>${snap.hijack.audio?`<audio controls src="${esc(snap.hijack.audio)}"></audio>`:''}<button class="danger" id="radioTakeBack">TAKE BACK CONTROL</button></div>`:'<div class="radioRow">No active hijack.</div>';
 if($('radioTakeBack'))$('radioTakeBack').onclick=async()=>{await api('radio_hq_takeback');load()};
 $('radioChallengeLive').innerHTML=snap.challenge?`<div class="radioRow"><b>${esc(snap.challenge.title)}</b><div>${esc(snap.challenge.instruction)}</div><strong>${Number(snap.challenge.prize||0)} MB</strong><br><small>${snap.challenge.completedAt?'✅ Auto-confirmed via #LizzyRadio':'Waiting for #LizzyRadio'}</small></div>`:'<div class="radioRow">No challenge live.</div>';
 $('radioTracks').innerHTML=mediaRows(snap.tracks||[],'track');$('radioAds').innerHTML=mediaRows(snap.ads||[],'ad');$('radioJingles').innerHTML=mediaRows(snap.jingles||[],'jingle');$('radioArchive').innerHTML=archiveRows();
 bindDynamic();renderLiveStatus();
}
function bindDynamic(){document.querySelectorAll('[data-attach]').forEach(b=>b.onclick=async()=>{const [kind,id]=b.dataset.attach.split(':');const file=document.querySelector(`[data-attach-file="${CSS.escape(kind+':'+id)}"]`)?.files?.[0],url=document.querySelector(`[data-attach-url="${CSS.escape(kind+':'+id)}"]`)?.value?.trim()||'';try{b.disabled=true;const audioData=await fileToDataUrl(file);await api('radio_hq_media_attach',{kind,id,url,audioData});await load()}catch(e){alert(e.message)}finally{b.disabled=false}});document.querySelectorAll('[data-delete-media]').forEach(b=>b.onclick=async()=>{const [kind,id]=b.dataset.deleteMedia.split(':');if(!confirm('Delete this radio media item?'))return;try{await api('radio_hq_media_delete',{kind,id});load()}catch(e){alert(e.message)}});document.querySelectorAll('[data-archive-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this archived broadcast and its saved audio?'))return;try{await api('radio_hq_archive_delete',{id:b.dataset.archiveDelete});load()}catch(e){alert(e.message)}})}
function renderLiveStatus(){const l=snap?.live,el=$('radioGoLiveStatus');if(!el)return;if(l?.active){const same=l.id===liveSession;el.innerHTML=`<b>🔴 ${esc(l.headline||'LIVE')}</b><br>${esc(stationName(l.station))}<br><small>${same?(livePc?.remoteDescription?'Listener connected / handshake complete':'Waiting for TESTR listener…'):'Live session active on the test network.'}</small>`}else el.textContent='Off air.'}
async function startLive(){if(liveStream)return alert('You are already live.');const station=val('rlStation'),headline=val('rlHeadline')||'Live from HQ';try{$('rlGo').disabled=true;$('radioGoLiveStatus').textContent='Opening microphone…';liveStream=await navigator.mediaDevices.getUserMedia({audio:true});livePc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});liveStream.getTracks().forEach(t=>livePc.addTrack(t,liveStream));const offer=await livePc.createOffer({offerToReceiveAudio:false});await livePc.setLocalDescription(offer);await waitIce(livePc);liveSession='live_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);liveChunks=[];let opts={};if(MediaRecorder.isTypeSupported('audio/webm;codecs=opus'))opts={mimeType:'audio/webm;codecs=opus',audioBitsPerSecond:32000};else if(MediaRecorder.isTypeSupported('audio/webm'))opts={mimeType:'audio/webm',audioBitsPerSecond:32000};liveRecorder=new MediaRecorder(liveStream,opts);liveRecorder.ondataavailable=e=>{if(e.data?.size)liveChunks.push(e.data)};liveRecorder.start(1000);await api('radio_hq_live_start',{session:liveSession,station,headline,offer:livePc.localDescription.sdp});liveStarted=Date.now();$('rlEnd').disabled=false;$('rlMute').disabled=false;$('radioGoLiveStatus').textContent='🔴 LIVE — waiting for TESTR listener…';livePoll=setInterval(checkLiveAnswer,1800);liveTimer=setInterval(()=>{const secs=Math.floor((Date.now()-liveStarted)/1000),m=Math.floor(secs/60),s=String(secs%60).padStart(2,'0');$('rlClock').textContent=`${m}:${s}`;if(Date.now()-liveStarted>=MAX_LIVE_MS)endLive(true)},1000);await load()}catch(e){cleanupLive();alert('Could not go live: '+e.message)}finally{$('rlGo').disabled=!!liveStream}}
async function checkLiveAnswer(){if(!liveSession||!livePc||livePc.remoteDescription)return;try{const d=await api('radio_hq_state'),l=d.state?.live;if(l?.id===liveSession&&l.answer){await livePc.setRemoteDescription({type:'answer',sdp:l.answer});$('radioGoLiveStatus').textContent='🔴 LIVE — TESTR listener connected ✓'}}catch(e){console.warn('live answer',e)}}
function toggleMute(){if(!liveStream)return;const t=liveStream.getAudioTracks()[0];if(!t)return;t.enabled=!t.enabled;$('rlMute').textContent=t.enabled?'🔇 Mute Mic':'🎙 Unmute Mic'}
async function endLive(auto=false){if(!liveStream||!liveSession)return;try{$('rlEnd').disabled=true;$('radioGoLiveStatus').textContent='Ending live broadcast and saving archive…';const session=liveSession;const rec=liveRecorder;const done=new Promise(resolve=>{if(!rec||rec.state==='inactive')return resolve();rec.addEventListener('stop',resolve,{once:true});rec.stop()});await done;const blob=new Blob(liveChunks,{type:rec?.mimeType||'audio/webm'});let audioData='';if(blob.size<=MAX_UPLOAD)audioData=await blobToDataUrl(blob);else alert('The live broadcast ended, but the recording was over 8 MB so it could not be stored in the test archive.');liveStream.getTracks().forEach(t=>t.stop());livePc?.close();clearInterval(livePoll);clearInterval(liveTimer);await api('radio_hq_live_end',{session,audioData});cleanupLive(false);$('radioGoLiveStatus').textContent=auto?'Live ended automatically at the 20-minute test archive limit.':'Live ended and archived ✓';await load()}catch(e){cleanupLive();alert('Live ended, but archiving failed: '+e.message)}}
function cleanupLive(stopTracks=true){if(stopTracks)liveStream?.getTracks()?.forEach(t=>t.stop());try{livePc?.close()}catch{}clearInterval(livePoll);clearInterval(liveTimer);livePc=null;liveStream=null;liveRecorder=null;liveChunks=[];liveSession='';liveStarted=0;if($('rlGo'))$('rlGo').disabled=false;if($('rlEnd'))$('rlEnd').disabled=true;if($('rlMute')){$('rlMute').disabled=true;$('rlMute').textContent='🔇 Mute Mic'}if($('rlClock'))$('rlClock').textContent='0:00'}
function mount(){const nav=document.querySelector('nav');if(nav&&!nav.querySelector('[data-view="radio"]'))nav.insertAdjacentHTML('beforeend','<button data-view="radio">📻 Radio Control</button>');const main=document.querySelector('main');if(!main||$('radio'))return;main.insertAdjacentHTML('beforeend',`<section id="radio" class="view hidden"><div class="section-intro"><div><span class="pill">🧪 TEST RADIO NETWORK</span><h2>📻 LizzyOS Radio Control</h2><p>Test-only radio control. Bundled songs play from TESTR; uploaded ads, jingles and live archives stay on the TEST Worker.</p></div><div class="intro-actions"><button class="primary" id="radioRefresh">↻ Refresh</button></div></div><div id="radioStatus" class="meta"></div><div class="radioGrid">
<div class="radioCard liveCard"><h3>🔴 Go Live from HQ</h3><select id="rlStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><input id="rlHeadline" placeholder="Breaking-news headline / live show title"><div class="liveControls"><button class="danger" id="rlGo">🎙 GO LIVE</button><button id="rlMute" disabled>🔇 Mute Mic</button><button id="rlEnd" disabled>⏹ End & Archive</button><strong id="rlClock">0:00</strong></div><div id="radioGoLiveStatus" class="liveStatus">Off air.</div><small>True browser-to-browser live audio. Each live session is recorded and archived when you end it. Test archive limit: 20 minutes / 8 MB.</small></div>
<div class="radioCard"><h3>Broadcast Now</h3><select id="rbStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><input id="rbTitle" placeholder="Headline / show title"><textarea id="rbText" placeholder="Broadcast text"></textarea><input id="rbAudio" placeholder="Optional audio URL/path"><input id="rbFile" type="file" accept="audio/*"><button class="primary" id="rbSend">Send Broadcast</button></div>
<div class="radioCard"><h3>Schedule Programme</h3><select id="rsStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><input id="rsTime" type="time" step="60" value="08:00"><input id="rsTitle" placeholder="Show title"><textarea id="rsText" placeholder="Optional show description"></textarea><button class="primary" id="rsAdd">Add Schedule</button><small>Schedule uses 24-hour HH:MM time.</small></div>
<div class="radioCard"><h3>Lizzy Radio Challenge</h3><input id="rcTitle" placeholder="Challenge title"><textarea id="rcInstruction" placeholder="e.g. Send Mikael a cute message with #LizzyRadio"></textarea><input id="rcPrize" type="number" min="0" placeholder="Prize MB"><button class="primary" id="rcStart">Start Challenge</button><div id="radioChallengeLive"></div></div>
<div class="radioCard wide"><h3>🎵 Music Library</h3><div class="radioForm"><input id="rmTitle" placeholder="Song title"><input id="rmArtist" placeholder="Artist"><input id="rmUrl" placeholder="Audio URL/path"><input id="rmFile" type="file" accept="audio/*"><div class="radio3">${STATIONS.map(([id,n])=>`<label><input type="checkbox" id="rm_${id}" checked> ${n.replace(' Radio','')}</label>`).join('')}</div><button class="primary" id="rmAdd">Add Track</button></div><div id="radioTracks" class="radioRows scrollRows"></div></div>
<div class="radioCard wide"><h3>📢 Fake Ad Library</h3><div class="radioForm"><input id="raTitle" placeholder="Company / advert name"><textarea id="raText" placeholder="Advert slogan / script"></textarea><select id="raFrequency"><option value="rare">Rare</option><option value="normal" selected>Normal</option><option value="frequent">Frequent</option></select><input id="raUrl" placeholder="Audio URL/path"><input id="raFile" type="file" accept="audio/*"><div class="radio3">${STATIONS.map(([id,n])=>`<label><input type="checkbox" id="ra_${id}" checked> ${n.replace(' Radio','')}</label>`).join('')}</div><button class="primary" id="raAdd">Add Advertisement</button></div><div id="radioAds" class="radioRows scrollRows"></div></div>
<div class="radioCard wide"><h3>🔊 Jingle / Breaking Sting Library</h3><div class="radioForm"><input id="rjTitle" placeholder="Jingle name"><select id="rjStation">${STATIONS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('')}</select><select id="rjKind"><option value="station">Station ID / opening</option><option value="show">Show transition</option><option value="breaking">Breaking-news sting</option></select><input id="rjUrl" placeholder="Audio URL/path"><input id="rjFile" type="file" accept="audio/*"><button class="primary" id="rjAdd">Add Jingle</button></div><div id="radioJingles" class="radioRows scrollRows"></div></div>
<div class="radioCard"><h3>Live Stations</h3><div id="radioLiveStations" class="radioRows"></div></div><div class="radioCard"><h3>Song / Voice Requests</h3><div id="radioRequests" class="radioRows"></div></div><div class="radioCard"><h3>Hijack Control</h3><div id="radioHijack"></div></div><div class="radioCard wide"><h3>🗃 Broadcast Archive</h3><div id="radioArchive" class="radioRows scrollRows"></div></div></div></section>`);
 nav?.querySelector('[data-view="radio"]')?.addEventListener('click',()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));nav.querySelector('[data-view="radio"]').classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('radio').classList.remove('hidden');$('viewTitle').textContent='LizzyOS Radio Control';load()});
 $('radioRefresh').onclick=load;$('rlGo').onclick=startLive;$('rlMute').onclick=toggleMute;$('rlEnd').onclick=()=>endLive(false);
 $('rbSend').onclick=async()=>{try{const audioData=await fileToDataUrl($('rbFile').files[0]);await api('radio_hq_broadcast',{station:val('rbStation'),title:val('rbTitle'),text:val('rbText'),audioUrl:val('rbAudio'),audioData});$('rbTitle').value='';$('rbText').value='';$('rbAudio').value='';$('rbFile').value='';load()}catch(e){alert(e.message)}};
 $('rsAdd').onclick=async()=>{try{await api('radio_hq_schedule',{station:val('rsStation'),time:val('rsTime'),title:val('rsTitle'),text:val('rsText')});load()}catch(e){alert(e.message)}};
 $('rcStart').onclick=async()=>{try{await api('radio_hq_challenge',{title:val('rcTitle'),instruction:val('rcInstruction'),prize:Number(val('rcPrize')||0)});load()}catch(e){alert(e.message)}};
 $('rmAdd').onclick=async()=>{try{const audioData=await fileToDataUrl($('rmFile').files[0]);await api('radio_hq_track',{title:val('rmTitle'),artist:val('rmArtist'),url:val('rmUrl'),audioData,stations:checkedStations('rm_')});$('rmFile').value='';load()}catch(e){alert(e.message)}};
 $('raAdd').onclick=async()=>{try{const audioData=await fileToDataUrl($('raFile').files[0]);await api('radio_hq_ad',{title:val('raTitle'),text:val('raText'),frequency:val('raFrequency'),url:val('raUrl'),audioData,stations:checkedStations('ra_')});$('raFile').value='';load()}catch(e){alert(e.message)}};
 $('rjAdd').onclick=async()=>{try{const audioData=await fileToDataUrl($('rjFile').files[0]);await api('radio_hq_jingle',{title:val('rjTitle'),station:val('rjStation'),kind:val('rjKind'),url:val('rjUrl'),audioData});$('rjFile').value='';load()}catch(e){alert(e.message)}};
}
window.addEventListener('beforeunload',()=>{if(liveStream)liveStream.getTracks().forEach(t=>t.stop())});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
