(()=>{
"use strict";
const $=id=>document.getElementById(id),api=(...a)=>window.MikaelHQApi(...a),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let snap=null,timer=null,lastSignature="",pendingSnapshot=null;
const LIFE_OUTBOX_KEY="testhq-life-outbox-v1";
function loadOutbox(){try{return JSON.parse(localStorage.getItem(LIFE_OUTBOX_KEY)||"[]")||[]}catch{return[]}}
function saveOutbox(x){try{localStorage.setItem(LIFE_OUTBOX_KEY,JSON.stringify(x.slice(-50)))}catch{}}
function commandId(){return globalThis.crypto?.randomUUID?.()||`hq-${Date.now()}-${Math.random().toString(36).slice(2)}`}
const COURT_KEY="mikaelLifeCourtTestV2";
function getCourtStore(){try{return JSON.parse(localStorage.getItem(COURT_KEY)||"{}")||{}}catch{return{}}}
function saveCourtStore(x){try{localStorage.setItem(COURT_KEY,JSON.stringify(x))}catch{}}
let courts=getCourtStore();
function lifeMinuteFromClock(v){const [h,m]=String(v||"19:00").split(":").map(Number);return Math.max(0,Math.min(1439,(h||0)*60+(m||0)))}
function badge(status){const s=String(status||"");return `<span class="lifeHQBadge ${esc(s)}">${esc(s.replace(/_/g," ").toUpperCase())}</span>`}
function editing(){const a=document.activeElement;return !!(a&&["INPUT","TEXTAREA","SELECT"].includes(a.tagName)&&a.closest("#life"))}
function stableSig(x){if(!x)return"";return JSON.stringify({lifeMinute:x.lifeMinute,cash:x.cash,job:x.job,loans:x.loans,legal:x.legal,interviews:x.interviews,pending:x.pending,relationship:x.relationship,officePeople:x.officePeople,family:x.family,spector:x.spector,activity:(x.activity||[]).slice(-5)})}
function answerBlock(i){if(!i.answers?.length)return '<div class="lifeHQEmpty">Interview scheduled / no answers submitted yet.</div>';return `<div class="lifeHQAnswers">${i.answers.map((a,idx)=>`<div class="lifeHQAnswer"><b>Q${idx+1}. ${esc(a.question)}</b><p>${esc(a.answer)}</p></div>`).join("")}</div>`}
function interviewCard(i){const c=i.contract||{},canAct=["awaiting_hq","countered","offer_received"].includes(i.status);const salary=Math.max(1,Number(c.counterSalary||c.salary||(i.source==="office"?55:85))||1),jobTitle=c.jobTitle||(i.source==="office"?"Assistant Regional Something Manager":"Special Presidential Adviser");return `<article class="lifeHQInterview">
 <div class="lifeHQInterviewHead"><div><b>${i.source==="office"?"📎":"🏛️"} ${esc(i.recruiter||"Interviewer")}</b><span>${esc(i.organization||"")} · ${esc(i.title||"Interview")}</span></div>${badge(i.status)}</div>
 ${answerBlock(i)}
 ${c.status?`<div class="lifeHQContractState"><b>Contract:</b> ${esc(c.status)}${c.salary?` · ${Math.round(c.salary)} LB/workday`:""}${c.counterSalary?`<br><strong>Lizzy countered: ${Math.round(c.counterSalary)} LB/workday</strong>`:""}</div>`:""}
 ${canAct?`<div class="lifeHQContractForm"><label>Job title</label><input data-contract-title="${esc(i.id)}" value="${esc(jobTitle)}"><label>Salary per workday (LB)</label><input data-contract-salary="${esc(i.id)}" type="number" min="1" value="${Math.round(salary)}"><label>Message / contract note</label><textarea data-contract-note="${esc(i.id)}" placeholder="Optional contract note…">${esc(c.note||"")}</textarea><div class="lifeHQRow"><button class="primary" data-contract-send="${esc(i.id)}">${i.status==="countered"?"🤝 Send Revised Contract":"📄 Send Proposed Contract"}</button><button class="danger" data-contract-reject="${esc(i.id)}">Reject Application</button></div></div>`:""}
 </article>`}
function legalTermsText(c){const t=c.terms||{};if(!t.type)return"Terms not synced yet";if(t.type==="probono")return"Pro bono";return `${String(t.type).replace(/_/g," ")} · ${t.value||"0"}`}
function legalRequestCard(c){return `<article class="lifeHQRequest"><div class="lifeHQInterviewHead"><div><b>⚖️ ${esc(c.defendant||"Unknown Defendant")}</b><span>Claim: ${Math.round(c.claimAmount||0)} LB</span></div>${badge(c.status)}</div><p>${esc(c.reason||"Case")}</p><label>Mikael Spector terms</label><select data-legal-terms="${esc(c.id)}"><option value="retainer">Retainer</option><option value="fixed">Fixed legal fee</option><option value="percentage">Settlement percentage</option><option value="combination">Combination</option><option value="probono">Pro bono</option></select><input data-legal-value="${esc(c.id)}" placeholder="Examples: 100 · 25 · 100 + 20%" value="100"><div class="lifeHQRow"><button data-life-legal="accept" data-id="${esc(c.id)}">⚖️ Take Case</button><button data-life-legal="reject" data-id="${esc(c.id)}" class="danger">Reject</button></div></article>`}
function courtStateFor(c){if(!courts[c.id])courts[c.id]={round:0,score:0,transcript:[],finished:false};return courts[c.id]}
const COURT_MOVES={
 opening:{label:"🎙️ Dramatic Opening",lines:["Mikael Spector opened by describing the matter as 'legally ridiculous but emotionally devastating'.","Counsel presented the claim with unnecessary confidence and excellent posture."],delta:[1,2]},
 evidence:{label:"📸 Present Evidence",lines:["A suspicious screenshot was entered into evidence. The judge zoomed in twice.","Exhibit A was presented. Nobody could explain why it had been laminated."],delta:[1,3]},
 cross:{label:"🧐 Cross-Examine",lines:["The defendant was asked one question too many and accidentally made Lizzy's case sound stronger.","Cross-examination revealed an alarming amount of workplace nonsense."],delta:[0,3]},
 object:{label:"☝️ Object Dramatically",lines:["Mikael Spector objected with such commitment that even the court reporter looked impressed.","An objection was sustained mainly because nobody wanted to hear the other side finish that sentence."],delta:[-1,2]},
 witness:{label:"🕵️ Surprise Witness",lines:["A surprise witness appeared and immediately asked whether parking would be reimbursed.","The surprise witness gave testimony that was 70% useful and 30% unrelated."],delta:[0,3]},
 closing:{label:"🎬 Closing Argument",lines:["Mikael Spector asked the court to choose justice, dignity, and a very specific number of Life Bucs.","The closing argument somehow referenced fairness, precedent and lunch theft."],delta:[1,3]}
};
function courtCard(c){const st=courtStateFor(c),moves=Object.entries(COURT_MOVES).map(([id,m])=>`<button data-court-move="${id}" data-id="${esc(c.id)}">${m.label}</button>`).join("");return `<article class="lifeHQCourt"><div class="lifeHQInterviewHead"><div><b>⚖️ ${esc(c.defendant||"Defendant")}</b><span>${esc(c.reason||"")} · Claim ${Math.round(c.claimAmount||0)} LB</span></div>${badge(c.status)}</div><p><b>Terms:</b> ${esc(legalTermsText(c))}</p><div class="courtScore"><span>Rounds <b>${st.round}</b></span><span>Court Momentum <b>${st.score>=0?"+":""}${st.score}</b></span></div><div class="lifeHQRow courtMoves">${moves}</div><div class="courtTranscript">${st.transcript.slice(-6).map((x,i)=>`<p><b>${Math.max(1,st.transcript.length-5+i)}.</b> ${esc(x)}</p>`).join("")||"<p>Court has not started yet.</p>"}</div><button class="primary" data-court-verdict="${esc(c.id)}" ${st.round<3||st.finished?"disabled":""}>⚖️ Ask Judge for Verdict</button>${st.round<3?'<small class="meta">Use at least 3 courtroom actions before asking for a verdict.</small>':""}${st.finished?'<small class="meta">Verdict has been queued to Lizzy Life.</small>':""}</article>`}
function closedCaseCard(c){const v=c.verdict||{};return `<article class="lifeHQRequest"><div class="lifeHQInterviewHead"><div><b>${v.won?"🏆":"⚖️"} ${esc(c.defendant||"Defendant")}</b><span>${esc(c.reason||"")}</span></div>${badge(c.status)}</div><p>${v.won?`Won ${Math.round(v.award||0)} LB. Lizzy net ${Math.round(v.net||0)} LB. Mikael Spector paid ${Math.round(v.paid||0)} LB.`:`Lost. Mikael Spector paid ${Math.round(v.paid||0)} LB.${v.outstanding?` ${Math.round(v.outstanding)} LB still due.`:""}`}</p><details><summary>📜 Court Transcript</summary>${(c.transcript||[]).map((x,i)=>`<p><b>${i+1}.</b> ${esc(typeof x==="string"?x:x.text||"")}</p>`).join("")||"No transcript."}</details></article>`}
function officeRelationships(){const ps=snap?.officePeople||{};return Object.values(ps).map(p=>`<div class="lifeHQLine"><b>${esc(p.name)}</b><span>${esc(p.status||"Coworkers")} · ❤️ ${Math.round(p.friendship||0)} · 🤝 ${Math.round(p.trust||0)} · ✨ ${Math.round(p.chemistry||0)} · 😤 ${Math.round(p.annoyance||0)}</span></div>`).join("")||'<div class="lifeHQEmpty">No Office relationships synced yet.</div>'}
function render(){
 const root=$("lifeHQBody"),status=$("lifeHQStatus");if(!root)return;
 if(!snap){root.innerHTML='<div class="card">Open Lizzy Life on the TEST site once so it can sync here.</div>';return}
 status.textContent=`● ${snap.date||"Life synced"} · Smart sync does not redraw while you type`;
 const loans=(snap.loans||[]).filter(x=>x.status==="pending"),legal=(snap.legal||[]).filter(x=>x.status==="requested"),court=(snap.legal||[]).filter(x=>x.status==="represented"),closed=(snap.legal||[]).filter(x=>x.status==="verdict").slice().reverse(),rel=snap.relationship?.mikael||{},ints=snap.interviews||[];
 const liveInts=ints.filter(i=>["scheduled","in_progress"].includes(i.status)),reviewInts=ints.filter(i=>!["scheduled","in_progress"].includes(i.status)).slice().reverse(),fam=snap.family||{},job=snap.job||{};
 root.innerHTML=`
 <div class="lifeHQTop">
   <div class="card"><small>LIZZY'S LIFE</small><h2>${esc(snap.date||"—")}</h2><p><b>${Math.round(Number(snap.cash)||0)} LB</b> · Activity-driven Life Time</p><div class="lifeHQNoReal">No real-world clock. HQ checks quietly every 15 seconds and will not redraw while you're editing.</div></div>
   <div class="card"><h3>❤️ Mikael Relationship</h3><div class="lifeHQStats"><span>Trust <b>${rel.trust??0}</b></span><span>Friendship <b>${rel.friendship??0}</b></span><span>Annoyance <b>${rel.annoyance??0}</b></span></div><p>Status: <b>${esc(rel.status||"Friends")}</b></p></div>
   <div class="card"><h3>💼 Current Life</h3><p><b>📍 ${esc((snap.location||"home").replace(/_/g," "))}</b></p><p>${job.employed?`${esc(job.organization||job.name)} — <b>${esc(job.title||"Employee")}</b><br>${job.salary} LB/workday · 09:00–17:00`:`Unemployed`}</p><div class="lifeHQStats"><span>Energy <b>${Math.round(snap.needs?.energy??0)}</b></span><span>Fun <b>${Math.round(snap.needs?.fun??0)}</b></span><span>Confidence <b>${Math.round(snap.needs?.confidence??0)}</b></span></div></div>
 </div>
 <div class="lifeHQGrid">
   <section class="card"><h3>💌 President Mikael Interaction</h3><label>Plan</label><select id="lifeHQPlan"><option>Shopping with Mikael</option><option>Dinner with Mikael</option><option>Bowling with Mikael</option><option>Presidential State Picnic</option><option>Emergency Chocolate Summit</option><option>Highly Suspicious Date</option></select><div class="lifeHQRow"><div><label>Life days from now</label><input id="lifeHQDays" type="number" min="1" max="365" value="2"></div><div><label>Life time</label><input id="lifeHQTime" type="time" value="19:00"></div></div><textarea id="lifeHQDetail" placeholder="Optional message from President Mikael…"></textarea><button class="primary" id="lifeHQInvite">Send Invitation</button><div id="lifeHQInviteResult" class="meta"></div></section>
   <section class="card"><h3>🏛️ President Mikael — Government Recruitment</h3><input id="lifeHQRecruitTitle" value="Office of President Mikael — Recruitment"><textarea id="lifeHQRecruitDetail">President Mikael would like to discuss a deeply important government role of questionable definition.</textarea><button class="primary" id="lifeHQRecruit">Send Government Recruitment</button><div id="lifeHQRecruitResult" class="meta"></div></section>
   <section class="card"><h3>📎 Michael Scott — The Office Recruitment</h3><input id="lifeHQOfficeRecruitTitle" value="Michael Scott — The Office Recruitment"><textarea id="lifeHQOfficeRecruitDetail">Michael Scott would like to interview Lizzy for a position at The Office. The exact responsibilities remain alarmingly unclear.</textarea><button class="primary" id="lifeHQOfficeRecruit">📎 Send Michael Scott Recruitment</button><div id="lifeHQOfficeRecruitResult" class="meta"></div></section>
 </div>
 <section class="card"><h3>🧑‍💼 Interview Review & Contract Negotiation</h3>${liveInts.length?`<h4>Scheduled / Live</h4>${liveInts.map(interviewCard).join("")}`:""}${reviewInts.length?reviewInts.map(interviewCard).join(""):'<div class="lifeHQEmpty">No completed interviews waiting yet.</div>'}</section>
 <div class="lifeHQGrid">
  <section class="card"><h3>💌 Mikael Date Request Delivery</h3><p class="meta">After you send a request, it appears here once Lizzy Life has received it.</p>${[...(snap.pending||[]).filter(x=>x.kind==="mikael_invite"),...(snap.plans||[]).filter(x=>x.withMikael)].slice(-8).reverse().map(x=>`<div class="lifeHQLine"><b>${esc(x.title||"Plan with Mikael")}</b><span>${esc((x.status||"pending").replace(/_/g," ").toUpperCase())}</span></div>`).join("")||'<div class="lifeHQEmpty">No Mikael date requests have been delivered yet.</div>'}</section>
  <section class="card"><h3>👔 Employer Controls</h3>${job.employed?`<p><b>${esc(job.organization||job.name)}</b><br>Current title: ${esc(job.title||"Employee")} · ${Math.round(job.salary||0)} LB/workday</p><label>New / promoted title</label><input id="lifeHQJobTitle" value="${esc(job.title||"Senior Employee")}"><label>Salary per workday</label><input id="lifeHQJobSalary" type="number" min="1" value="${Math.round(job.salary||1)}"><label>Fire reason</label><textarea id="lifeHQFireReason">${esc(job.boss||"The boss")} has decided Lizzy's employment is no longer aligned with the organisation's deeply confusing strategic vision.</textarea><div class="lifeHQRow"><button class="primary" data-employment="promote">⬆️ Promote / Update Salary</button><button data-employment="title">🪪 Change Title</button><button class="danger" data-employment="fire">🔥 Fire Lizzy</button></div>`:'<div class="lifeHQEmpty">Lizzy is currently unemployed.</div>'}</section>
  <section class="card"><h3>📎 The Office Relationships</h3>${officeRelationships()}</section>
 </div>
 <div class="lifeHQGrid">
   <section class="card"><h3>🏦 Bank of Micky — Pending Loans</h3>${loans.length?loans.map(l=>`<article class="lifeHQRequest"><div><b>${Math.round(l.amount)} LB</b> · ${esc(l.purpose||"Loan")}</div>${badge(l.status)}<div class="lifeHQRow"><input data-life-payment="${esc(l.id)}" type="number" min="1" value="${Math.max(1,Math.ceil(Number(l.amount||0)/6))}"><button data-life-loan="approve" data-id="${esc(l.id)}">✅ Approve</button><button data-life-loan="reject" data-id="${esc(l.id)}" class="danger">❌ Reject</button></div></article>`).join(""):'<div class="lifeHQEmpty">No loan applications waiting.</div>'}</section>
   <section class="card"><h3>⚖️ Mikael Spector — New Legal Requests</h3><p class="meta">Spector earned: <b>${Math.round(snap.spector?.earned||0)} LB</b>${snap.spector?.outstanding?` · Outstanding legal fees: <b>${Math.round(snap.spector.outstanding)} LB</b>`:""}</p>${legal.length?legal.map(legalRequestCard).join(""):'<div class="lifeHQEmpty">No new representation requests waiting.</div>'}</section>
 </div>
 <section class="card"><h3>🏛️ Mikael Spector Court Docket</h3><p class="meta">Cases you accept appear here. Use courtroom moves, build momentum, then ask the judge for a verdict. The full transcript and money result are sent back to Lizzy automatically.</p>${court.length?court.map(courtCard).join(""):'<div class="lifeHQEmpty">No represented cases are ready for court.</div>'}</section>
 ${closed.length?`<section class="card"><h3>📚 Closed Court Cases</h3>${closed.slice(0,8).map(closedCaseCard).join("")}</section>`:""}
 <div class="lifeHQGrid"><section class="card"><h3>👨‍👩‍👧 Family Temperature</h3>${Object.values(fam).map(p=>`<div class="lifeHQLine"><b>${esc(p.name||"Family")}</b><span>❤️ ${Math.round(p.friendship||0)} · 🤝 ${Math.round(p.trust||0)} · 😤 ${Math.round(p.annoyance||0)}</span></div>`).join("")||'<div class="lifeHQEmpty">No family data yet.</div>'}</section><section class="card"><h3>📰 Recent Life Activity</h3>${(snap.activity||[]).slice().reverse().slice(0,14).map(a=>`<div class="lifeHQLine"><b>${esc(a.icon||"•")} Day ${(a.day??0)+1}</b><span>${esc(a.text)}</span></div>`).join("")||'<div class="lifeHQEmpty">Nothing yet.</div>'}</section></div>`;
 bind();
}
async function flushOutbox(){const box=loadOutbox();if(!box.length)return 0;const keep=[];let sent=0;for(const command of box){try{await api("life_hq_push",{command});sent++}catch{keep.push(command);break}}saveOutbox([...keep,...box.slice(sent+keep.length)]);return sent}
async function send(command){const c={...command,id:command.id||commandId()};try{const d=await api("life_hq_push",{command:c});const box=loadOutbox().filter(x=>x.id!==c.id);saveOutbox(box);return d}catch(e){const box=loadOutbox();if(!box.some(x=>x.id===c.id)){box.push(c);saveOutbox(box)}throw new Error(`${e.message} · Saved in HQ outbox for retry.`)}}
async function afterAction(button,label="Queued ✓"){if(button)button.textContent=label;setTimeout(()=>load({force:false}),350)}
function bind(){
 $("lifeHQInvite")?.addEventListener("click",async()=>{const r=$("lifeHQInviteResult");try{const d=await send({kind:"life_invite",title:$("lifeHQPlan").value,detail:$("lifeHQDetail").value.trim(),daysAhead:Math.max(1,Number($("lifeHQDays").value)||1),timeMinute:lifeMinuteFromClock($("lifeHQTime").value)});r.textContent=`✅ Date request queued${d?.command?.id?` · ${d.command.id}`:""}. It will appear as delivered below after Lizzy Life receives it.`}catch(e){r.textContent="❌ "+e.message}});
 $("lifeHQRecruit")?.addEventListener("click",async()=>{const r=$("lifeHQRecruitResult");try{await send({kind:"recruitment",source:"government",recruiter:"President Mikael",organization:"Government",title:$("lifeHQRecruitTitle").value,detail:$("lifeHQRecruitDetail").value});r.textContent="✅ Government recruitment queued."}catch(e){r.textContent="❌ "+e.message}});
 $("lifeHQOfficeRecruit")?.addEventListener("click",async()=>{const r=$("lifeHQOfficeRecruitResult");try{await send({kind:"recruitment",source:"office",recruiter:"Michael Scott",organization:"The Office",title:$("lifeHQOfficeRecruitTitle").value,detail:$("lifeHQOfficeRecruitDetail").value});r.textContent="✅ Michael Scott recruitment queued."}catch(e){r.textContent="❌ "+e.message}});
 document.querySelectorAll("[data-contract-send]").forEach(b=>b.onclick=async()=>{const id=b.dataset.contractSend,title=document.querySelector(`[data-contract-title="${CSS.escape(id)}"]`)?.value||"Role",salary=Number(document.querySelector(`[data-contract-salary="${CSS.escape(id)}"]`)?.value)||1,note=document.querySelector(`[data-contract-note="${CSS.escape(id)}"]`)?.value||"";try{await send({kind:"contract_offer",interviewId:id,jobTitle:title,salary,note});afterAction(b)}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-contract-reject]").forEach(b=>b.onclick=async()=>{if(!confirm("Reject this application?"))return;try{await send({kind:"hiring_decision",interviewId:b.dataset.contractReject,decision:"reject"});afterAction(b,"Rejected ✓")}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-life-loan]").forEach(b=>b.onclick=async()=>{const id=b.dataset.id,decision=b.dataset.lifeLoan,payment=Number(document.querySelector(`[data-life-payment="${CSS.escape(id)}"]`)?.value)||0;try{await send({kind:"loan_decision",requestId:id,decision,payment});afterAction(b)}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-life-legal]").forEach(b=>b.onclick=async()=>{const id=b.dataset.id,decision=b.dataset.lifeLegal,type=document.querySelector(`[data-legal-terms="${CSS.escape(id)}"]`)?.value,value=document.querySelector(`[data-legal-value="${CSS.escape(id)}"]`)?.value;try{await send({kind:"legal_decision",requestId:id,decision,terms:{type,value}});afterAction(b,decision==="accept"?"Case accepted ✓":"Rejected ✓")}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-employment]").forEach(b=>b.onclick=async()=>{const action=b.dataset.employment,title=$("lifeHQJobTitle")?.value||"Employee",salary=Math.max(1,Number($("lifeHQJobSalary")?.value)||1),reason=$("lifeHQFireReason")?.value||"Employment terminated by HQ.";if(action==="fire"&&!confirm("Fire Lizzy from her current job?"))return;try{await send({kind:"employment_action",action,title,salary,reason});afterAction(b,action==="fire"?"Firing queued ✓":"Update queued ✓")}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-court-move]").forEach(b=>b.onclick=()=>{const id=b.dataset.id,c=(snap.legal||[]).find(x=>x.id===id),move=COURT_MOVES[b.dataset.courtMove];if(!c||!move)return;const st=courtStateFor(c),delta=Math.floor(move.delta[0]+Math.random()*(move.delta[1]-move.delta[0]+1)),line=move.lines[Math.floor(Math.random()*move.lines.length)];st.round++;st.score+=delta;st.transcript.push(`${move.label}: ${line} (${delta>=0?"+":""}${delta} momentum)`);courts[id]=st;saveCourtStore(courts);render()});
 document.querySelectorAll("[data-court-verdict]").forEach(b=>b.onclick=async()=>{const id=b.dataset.courtVerdict,c=(snap.legal||[]).find(x=>x.id===id),st=courtStateFor(c);if(!c||st.round<3||st.finished)return;const judgeRoll=Math.floor(Math.random()*4)-1,total=st.score+judgeRoll,won=total>=3,base=Math.max(100,Number(c.claimAmount)||500),award=won?Math.max(50,Math.round(base*(0.75+Math.random()*.5)/10)*10):0,judgeNote=won?"The court found that the nonsense crossed the legally tolerable threshold.":"The court found the nonsense real, but not expensive enough today.",summary=won?`Lizzy wins against ${c.defendant} and is awarded ${award} LB.`:`The claim against ${c.defendant} is dismissed.`;st.transcript.push(`JUDGE: ${judgeNote}`);st.transcript.push(`VERDICT: ${summary}`);try{await send({kind:"court_verdict",requestId:id,won,award,judgeNote,summary,transcript:st.transcript});st.finished=true;courts[id]=st;saveCourtStore(courts);b.textContent="Verdict queued to Lizzy ✓"}catch(e){alert(e.message)}});
}
async function load({force=false}={}){if(!window.MikaelHQApi)return;try{const d=await api("life_snapshot_get"),fresh=d.snapshot||null,sig=stableSig(fresh);if(!force&&editing()){pendingSnapshot=fresh;if($("lifeHQStatus"))$("lifeHQStatus").textContent="● New Life data checked · screen held steady while you edit";return}if(!force&&sig===lastSignature)return;snap=fresh;pendingSnapshot=null;lastSignature=sig;render()}catch(e){if($("lifeHQStatus"))$("lifeHQStatus").textContent=e.message}}
function start(){flushOutbox().catch(()=>{});load({force:true});clearInterval(timer);timer=setInterval(()=>{if(!$("life")?.classList.contains("hidden"))load({force:false})},30000)}
$("lifeHQRefresh")?.addEventListener("click",()=>load({force:true}));document.querySelector('[data-view="life"]')?.addEventListener("click",start);window.MikaelLifeHQ={load,start};
})();
