(()=>{
"use strict";
const $=id=>document.getElementById(id),api=(...a)=>window.MikaelHQApi(...a),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
let snap=null,timer=null;
function lifeMinuteFromClock(v){const [h,m]=String(v||"19:00").split(":").map(Number);return Math.max(0,Math.min(1439,(h||0)*60+(m||0)))}
function badge(status){const s=String(status||"");return `<span class="lifeHQBadge ${esc(s)}">${esc(s.replace(/_/g," ").toUpperCase())}</span>`}
function answerBlock(i){if(!i.answers?.length)return '<div class="lifeHQEmpty">Interview scheduled / no answers submitted yet.</div>';return `<div class="lifeHQAnswers">${i.answers.map((a,idx)=>`<div class="lifeHQAnswer"><b>Q${idx+1}. ${esc(a.question)}</b><p>${esc(a.answer)}</p></div>`).join("")}</div>`}
function interviewCard(i){const c=i.contract||{},canAct=["awaiting_hq","countered","offer_received"].includes(i.status);const salary=Math.max(1,Number(c.counterSalary||c.salary||(i.source==="office"?55:85))||1),jobTitle=c.jobTitle||(i.source==="office"?"Assistant Regional Something Manager":"Special Presidential Adviser");return `<article class="lifeHQInterview">
 <div class="lifeHQInterviewHead"><div><b>${i.source==="office"?"📎":"🏛️"} ${esc(i.recruiter||"Interviewer")}</b><span>${esc(i.organization||"")} · ${esc(i.title||"Interview")}</span></div>${badge(i.status)}</div>
 ${answerBlock(i)}
 ${c.status?`<div class="lifeHQContractState"><b>Contract:</b> ${esc(c.status)}${c.salary?` · ${Math.round(c.salary)} LB/workday`:""}${c.counterSalary?`<br><strong>Lizzy countered: ${Math.round(c.counterSalary)} LB/workday</strong>`:""}</div>`:""}
 ${canAct?`<div class="lifeHQContractForm"><label>Job title</label><input data-contract-title="${esc(i.id)}" value="${esc(jobTitle)}"><label>Salary per workday (LB)</label><input data-contract-salary="${esc(i.id)}" type="number" min="1" value="${Math.round(salary)}"><label>Message / contract note</label><textarea data-contract-note="${esc(i.id)}" placeholder="Optional contract note…">${esc(c.note||"")}</textarea><div class="lifeHQRow"><button class="primary" data-contract-send="${esc(i.id)}">${i.status==="countered"?"🤝 Send Revised Contract":"📄 Send Proposed Contract"}</button><button class="danger" data-contract-reject="${esc(i.id)}">Reject Application</button></div></div>`:""}
 </article>`}
function render(){
 const root=$("lifeHQBody"),status=$("lifeHQStatus");if(!root)return;
 if(!snap){root.innerHTML='<div class="card">Open Lizzy Life on the TEST site once so it can sync here.</div>';return}
 status.textContent=`● ${snap.date||"Life synced"}`;
 const loans=(snap.loans||[]).filter(x=>x.status==="pending"),legal=(snap.legal||[]).filter(x=>x.status==="requested"),rel=snap.relationship?.mikael||{},ints=snap.interviews||[];
 const liveInts=ints.filter(i=>["scheduled","in_progress"].includes(i.status)),reviewInts=ints.filter(i=>!["scheduled","in_progress"].includes(i.status)).slice().reverse();
 const fam=snap.family||{};
 root.innerHTML=`
 <div class="lifeHQTop">
   <div class="card"><small>LIZZY'S LIFE</small><h2>${esc(snap.date||"—")}</h2><p><b>${Math.round(Number(snap.cash)||0)} LB</b> · Activity-driven Life Time</p><div class="lifeHQNoReal">No real-world clock. Time changes only when Lizzy completes a timed activity or explicitly skips Life time.</div></div>
   <div class="card"><h3>❤️ Mikael Relationship</h3><div class="lifeHQStats"><span>Trust <b>${rel.trust??0}</b></span><span>Friendship <b>${rel.friendship??0}</b></span><span>Annoyance <b>${rel.annoyance??0}</b></span></div><p>Status: <b>${esc(rel.status||"Friends")}</b></p></div>
   <div class="card"><h3>💼 Current Life</h3><p><b>📍 ${esc((snap.location||"home").replace(/_/g," "))}</b></p><p>${snap.job?.employed?`${esc(snap.job.name)} · ${snap.job.salary} LB/workday · 09:00–17:00`:`Unemployed`}</p><div class="lifeHQStats"><span>Energy <b>${Math.round(snap.needs?.energy??0)}</b></span><span>Fun <b>${Math.round(snap.needs?.fun??0)}</b></span><span>Confidence <b>${Math.round(snap.needs?.confidence??0)}</b></span></div></div>
 </div>
 <div class="lifeHQGrid">
   <section class="card"><h3>💌 President Mikael Interaction</h3><p class="meta">Send a protected invitation. Travel to the event does not use Life time; the activity itself can.</p><label>Plan</label><select id="lifeHQPlan"><option>Shopping with Mikael</option><option>Dinner with Mikael</option><option>Bowling with Mikael</option><option>Presidential State Picnic</option><option>Emergency Chocolate Summit</option><option>Highly Suspicious Date</option></select><div class="lifeHQRow"><div><label>Life days from now</label><input id="lifeHQDays" type="number" min="1" max="365" value="2"></div><div><label>Life time</label><input id="lifeHQTime" type="time" value="19:00"></div></div><textarea id="lifeHQDetail" placeholder="Optional message from President Mikael…"></textarea><button class="primary" id="lifeHQInvite">Send Invitation</button><div id="lifeHQInviteResult" class="meta"></div></section>
   <section class="card"><h3>🏛️ President Mikael — Government Recruitment</h3><p class="meta">If Lizzy accepts, the interview is automatically scheduled for <b>09:00 the next Life day</b> in the Morning slot. President Mikael will ask 3 nonsensical political questions.</p><input id="lifeHQRecruitTitle" value="Office of President Mikael — Recruitment"><textarea id="lifeHQRecruitDetail">President Mikael would like to discuss a deeply important government role of questionable definition.</textarea><button class="primary" id="lifeHQRecruit">Send Government Recruitment</button><div id="lifeHQRecruitResult" class="meta"></div></section>
   <section class="card"><h3>📎 Michael Scott — The Office Recruitment</h3><p class="meta">If Lizzy accepts, Michael's interview is scheduled for 09:00 the next Life day. He will ask 3 original nonsensical office questions.</p><input id="lifeHQOfficeRecruitTitle" value="Michael Scott — The Office Recruitment"><textarea id="lifeHQOfficeRecruitDetail">Michael Scott would like to interview Lizzy for a position at The Office. The exact responsibilities remain alarmingly unclear.</textarea><button class="primary" id="lifeHQOfficeRecruit">📎 Send Michael Scott Recruitment</button><div id="lifeHQOfficeRecruitResult" class="meta"></div></section>
 </div>
 <section class="card"><h3>🧑‍💼 Interview Review & Contract Negotiation</h3><p class="meta">Lizzy's three questions and typed answers arrive here automatically after she submits the interview. You can then offer a salary, revise it after a counter, or reject the application.</p>${liveInts.length?`<h4>Scheduled / Live</h4>${liveInts.map(interviewCard).join("")}`:""}${reviewInts.length?reviewInts.map(interviewCard).join(""):'<div class="lifeHQEmpty">No completed interviews waiting yet.</div>'}</section>
 <div class="lifeHQGrid">
   <section class="card"><h3>🏦 Bank of Micky — Pending Loans</h3>${loans.length?loans.map(l=>`<article class="lifeHQRequest"><div><b>${Math.round(l.amount)} LB</b> · ${esc(l.purpose||"Loan")}</div>${badge(l.status)}<div class="lifeHQRow"><input data-life-payment="${esc(l.id)}" type="number" min="1" value="${Math.max(1,Math.ceil(Number(l.amount||0)/6))}"><button data-life-loan="approve" data-id="${esc(l.id)}">✅ Approve</button><button data-life-loan="reject" data-id="${esc(l.id)}" class="danger">❌ Reject</button></div></article>`).join(""):'<div class="lifeHQEmpty">No loan applications waiting.</div>'}</section>
   <section class="card"><h3>⚖️ Mikael Spector — Legal Requests</h3>${legal.length?legal.map(l=>`<article class="lifeHQRequest"><div><b>${esc(l.reason||"Case")}</b></div>${badge(l.status)}<label>Terms</label><select data-legal-terms="${esc(l.id)}"><option value="retainer">Retainer</option><option value="fixed">Fixed legal fee</option><option value="percentage">Settlement percentage</option><option value="combination">Combination</option><option value="probono">Pro bono</option></select><input data-legal-value="${esc(l.id)}" placeholder="Amount / % / terms" value="100"><div class="lifeHQRow"><button data-life-legal="accept" data-id="${esc(l.id)}">⚖️ Take Case</button><button data-life-legal="reject" data-id="${esc(l.id)}" class="danger">Reject</button></div></article>`).join(""):'<div class="lifeHQEmpty">No legal representation requests waiting.</div>'}</section>
 </div>
 <div class="lifeHQGrid">
   <section class="card"><h3>👨‍👩‍👧 Family Temperature</h3>${Object.values(fam).map(p=>`<div class="lifeHQLine"><b>${esc(p.name||"Family")}</b><span>❤️ ${Math.round(p.friendship||0)} · 🤝 ${Math.round(p.trust||0)} · 😤 ${Math.round(p.annoyance||0)}</span></div>`).join("")||'<div class="lifeHQEmpty">No family data yet.</div>'}</section>
   <section class="card"><h3>📰 Recent Life Activity</h3>${(snap.activity||[]).slice().reverse().slice(0,14).map(a=>`<div class="lifeHQLine"><b>${esc(a.icon||"•")} Day ${(a.day??0)+1}</b><span>${esc(a.text)}</span></div>`).join("")||'<div class="lifeHQEmpty">Nothing yet.</div>'}</section>
 </div>`;
 bind();
}
function bind(){
 $("lifeHQInvite")?.addEventListener("click",async()=>{const r=$("lifeHQInviteResult");try{await api("life_hq_push",{command:{kind:"life_invite",title:$("lifeHQPlan").value,detail:$("lifeHQDetail").value.trim(),daysAhead:Math.max(1,Number($("lifeHQDays").value)||1),timeMinute:lifeMinuteFromClock($("lifeHQTime").value)}});r.textContent="✅ Invitation queued for Lizzy Life."}catch(e){r.textContent="❌ "+e.message}});
 $("lifeHQRecruit")?.addEventListener("click",async()=>{const r=$("lifeHQRecruitResult");try{await api("life_hq_push",{command:{kind:"recruitment",source:"government",recruiter:"President Mikael",organization:"Government",title:$("lifeHQRecruitTitle").value,detail:$("lifeHQRecruitDetail").value}});r.textContent="✅ Government recruitment queued."}catch(e){r.textContent="❌ "+e.message}});
 $("lifeHQOfficeRecruit")?.addEventListener("click",async()=>{const r=$("lifeHQOfficeRecruitResult");try{await api("life_hq_push",{command:{kind:"recruitment",source:"office",recruiter:"Michael Scott",organization:"The Office",title:$("lifeHQOfficeRecruitTitle").value,detail:$("lifeHQOfficeRecruitDetail").value}});r.textContent="✅ Michael Scott recruitment queued."}catch(e){r.textContent="❌ "+e.message}});
 document.querySelectorAll("[data-contract-send]").forEach(b=>b.onclick=async()=>{const id=b.dataset.contractSend,title=document.querySelector(`[data-contract-title="${CSS.escape(id)}"]`)?.value||"Role",salary=Number(document.querySelector(`[data-contract-salary="${CSS.escape(id)}"]`)?.value)||1,note=document.querySelector(`[data-contract-note="${CSS.escape(id)}"]`)?.value||"";try{await api("life_hq_push",{command:{kind:"contract_offer",interviewId:id,jobTitle:title,salary,note}});b.textContent="Contract queued ✓"}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-contract-reject]").forEach(b=>b.onclick=async()=>{if(!confirm("Reject this application?"))return;try{await api("life_hq_push",{command:{kind:"hiring_decision",interviewId:b.dataset.contractReject,decision:"reject"}});b.textContent="Rejected ✓"}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-life-loan]").forEach(b=>b.onclick=async()=>{const id=b.dataset.id,decision=b.dataset.lifeLoan,payment=Number(document.querySelector(`[data-life-payment="${CSS.escape(id)}"]`)?.value)||0;try{await api("life_hq_push",{command:{kind:"loan_decision",requestId:id,decision,payment}});b.textContent="Queued ✓"}catch(e){alert(e.message)}});
 document.querySelectorAll("[data-life-legal]").forEach(b=>b.onclick=async()=>{const id=b.dataset.id,decision=b.dataset.lifeLegal,type=document.querySelector(`[data-legal-terms="${CSS.escape(id)}"]`)?.value,value=document.querySelector(`[data-legal-value="${CSS.escape(id)}"]`)?.value;try{await api("life_hq_push",{command:{kind:"legal_decision",requestId:id,decision,terms:{type,value}}});b.textContent="Queued ✓"}catch(e){alert(e.message)}});
}
async function load(){if(!window.MikaelHQApi)return;try{const d=await api("life_snapshot_get");snap=d.snapshot||null;render()}catch(e){if($("lifeHQStatus"))$("lifeHQStatus").textContent=e.message}}
function start(){load();clearInterval(timer);timer=setInterval(()=>{if(!$("life")?.classList.contains("hidden"))load()},5000)}
$("lifeHQRefresh")?.addEventListener("click",load);document.querySelector('[data-view="life"]')?.addEventListener("click",start);window.MikaelLifeHQ={load,start};
})();
